### ISSUE TITLE
Assignment 2.7 string_copy definition doesn't match test harness or solution code

### ISSUE THREAD

**Issue by jackc** [Apress/low-level-programming#17]
The definition for string_copy:

> Accepts a pointer to a string, a pointer to a buffer, and buffer's length. Copies string to the destination. The destination address is returned if the string fits the buffer; otherwise zero is returns.

This is similar to `strncpy` in C. But the provided solution is the equivalent of `strcpy`. And because the caller in the test harness doesn't provide the buffer length in `rdx` an implementation that implements the behaviour described in the book will not pass the test.

**Comment by sayon** [comment]
Thank you for reporting it, I am sorry for this inconsistency. 
 For now we can stay with an unsafe version with only two arguments (equivalent of `strcpy`) and once I submit the rest of assignments/answers I'll replace the code to match the book text.

**Comment by sayon** [comment]
fixed in #57
