### ISSUE TITLE
Assignment 2.7 read_word definition doesn't match test harness or solution code 

### ISSUE THREAD

**Issue by jackc** [Apress/low-level-programming#20]
The definition for `read_word`:

> Accepts a buffer address and size as arguments ...

Test harness and code appear to expect `read_word` to use `word_buffer` memory location instead of arguments.

**Comment by sayon** [comment]
Thank you for reporting this. It should be fixed in #23. Please tell me if this worked for you -- I've added some more tests as well.

**Comment by jackc** [comment]
I get further this time, but the last test for `read_word` doesn't match the requirements in the book. 

> Stops and returns 0 if word is too big for the buffer specified; otherwise returns a buffer address.

The test:

```
          testing read_word on "asdbaskdbaksvbaskvhbashvbasdasdads wewe"
  read_word : compiled
" asdbaskdbaksvbaskvhbashvbasdasdads wewe " -> ('asdbaskdbaksvbaskvh', 0)
  [   ok   ]
```

The first 19 characters + terminating null expected by the test harness and sample code - whereas the book requirements are to return 0 when too big.

Also, I found an errata at the end of the chapter (sorry, I bought the book on Kindle so I don't have real page numbers). Footnote 7 lists the codes for what is considered whitespace. 0x10 is not new line. It should be 0xA or decimal 10.

**Comment by sayon** [comment]
0. It seems that there is a missing point in read_word description: it should return the word length in rdx. I'll add that to errata
1. Sorry for the bad specs,  #26 should do it. I've taken liberty in poking your solution and after uncommenting the lines 189-190 to enable returning string length in `rdx` the `read_word` tests are being passed correctly.
2. Thanks for reporting the error in the footnote, I am fixing it. This is unfortunate, I've not imagined Kindle version will have different page numbers. I am going to put section numbers in the errata as well. Are all footnotes shown at the end of the chapter?

**Comment by jackc** [comment]
:+1: Works now. Thanks!

Kindle reformats for the size of device so it doesn't have real page numbers. Section numbers would be great for errata. And yes, footnotes are at the end of the chapter.
