### ISSUE TITLE
Answers to Questions 27 & 28 don't reflect reference on page 26

### ISSUE THREAD

**Issue by pperon** [Apress/low-level-programming#30]
For example the answer to 27 (callee-saved registers) is listed as: rax, rcx, rdx, rdi, rsi, r8-r1.
While the book references: rbx, rbp, rsp, r12-r15.

**Comment by sayon** [comment]
Thank you for reporting, the answers should be swapped. Fixed in #31 .
I'll get back to committing missing answers soon.
