### ISSUE TITLE
VM user

### ISSUE THREAD

**Issue by tsmckelvey** [Apress/low-level-programming#32]
Upon booting VM must provide username/password for valid user.  I would expect to find this information in the README.

**Comment by sayon** [comment]
Thank you for reporting! My fault.

login: user
pass: user
root pass: qwerty

Will update the README in the next commit.

**Comment by sayon** [comment]
Fixed in #33 e

**Comment by tsmckelvey** [comment]
That was fast!  Thanks!  Really enjoying the book so far :)
