### ISSUE TITLE
Listing 5-31. libso corrupt?

### ISSUE THREAD

**Issue by kneoyskw** [Apress/low-level-programming#40]
something wrong with 2 command lines in Listing 5-31.
After two nasm lines, the book says:

> ld -o main.o -d libso.so
> ld -shared -o libso.so libso.o --dynamic-linker=/lib64/ld-linux-x86-64.so2

which does not work because libso.so is not yet generated.
Refering to the Makefile in libso directory and making it all right,
i guessed that the 2 lines shown above should be replaced with:

> ld -shared -o libso.so libso.o
> ld -o main main.o -d libso.so --dynamic-linker=/lib64/ld-linux-x86-64.so.2

**Comment by sayon** [comment]
Fixed in #49. Thank you!
