### ISSUE TITLE
login on minimal.vmdk

### ISSUE THREAD

**Issue by MaloneyBaloney14** [Apress/low-level-programming#41]
I purchased Kindle version.  Installed the .vmdk on Virtual Box.  The Debian prompts for a login.  I haven't been able to find this login information.  How can I learn the login?

**Comment by sayon** [comment]
Hello! It is in README.md file in the root directory of this repository:

Username: user, password: user, root password: qwerty

**Comment by MaloneyBaloney14** [comment]
I'm sorry I should have seen that.  I was under heavy cognitive load.

I'm running into another hurdle and have tried to search info, but haven't found the insight.

Why does the VM download include s001, s002, s003, s004, s005, and s006.vmdk?

I have installed the minimal.vmdk in VirtualBox.  It seems to run okay.  Now I'm in Appendix A trying to use the debugger.  In the Debian setup I type ( ls -ah) in the home directory.  There's no indication of a gdbinit file.  Is gdb installed on the minimal.vmdk?  Or is it on the other versions?

I'm sorry if I haven't been able to locate this information.

**Comment by sayon** [comment]
@MaloneyBaloney14 `.gdbinit` is the configuration file for `gdb` debugger. If it does not exist, you can create it in the text editor of your choice and fill with the commands you want to be autoexecuted on each gdb startup. 

For example:
```
set disassembly-flavor intel
```

to switch from AT&T to Intel assembly syntax.
