### ISSUE TITLE
11.7.2 Assignment #6. "the modules" not clear

### ISSUE THREAD

**Issue by kneoyskw** [Apress/low-level-programming#42]
On page 218 of the book, in the section
"11.7 Assignment: Higher-Order Functions and Lists"
It says "6. Implement `map_mut`; using it,
output **the modules** of the input numbers"
I am wondering what "the modules" mean.

**Comment by sayon** [comment]
Sorry, it is a typo: I meant absolute values.

abs(x) = x if x >=0, -x if x < 0.
