### ISSUE TITLE
SSH into VM not working

### ISSUE THREAD

**Issue by ukolka** [Apress/low-level-programming#54]
I had an issue connecting to the VM. In the end networking turned out to be misconfigured.
In _/etc/network/interfaces_ I replaced **ens33** with **enp0s3** which is what my `$sudo ip a` has shown.

**Comment by sayon** [comment]
I am not sure I do know how to configure network on a virtual machine in a way it just works for everyone out of the box. It highly depends on the host VM configuration, of which I have no control. Would you  maybe suggest an idea? I have no prior experience with docker; would it make for a better solution?

**Comment by ukolka** [comment]
I can't think of a reliable solution either. Nevertheless there's a merit in reporting this for future reference, should anybody else have this problem. Regarding Docker - there are portability issues.
Since with Docker guest uses host's kernel it's not possible to run Linux on Windows, for example.
