### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by mikemadden42** [Apress/low-level-programming#67]
That's awesome that preconfigured Linux virtual machines are available.  Is there any interest in supporting Docker?  I could put together a Dockerfile, get the image into Docker Hub, and provide some directions if it would be useful.

**Comment by sayon** [comment]
Hello, it would be amazing! Thanks for your proposal. I have not used docker yet, so I could not be much of a help here. 
I found something a japanese guy made, maybe that could be of a use for you:
http://weblog.metacircular-evaluator.org/blog/2018/01/28/low-level-programming-memo/

Thanks again!

**Comment by kellyi** [comment]
Hi! I just started reading this book (which is great, btw!) and I set up a Docker Debian/jessie environment with NASM, GCC, GDB, Make and Vim installed, along with some instructions for getting it running, here:

https://github.com/kellyi/nasm-gcc-container

I used docker-compose to mount a dir from host to guest which means that you can use whatever editor you want on your guest, save the files in `nasm-gcc/src` and then they'll be available for compilation and linking inside the running container.

Thanks so much for writing the book!

**Comment by sayon** [comment]
I am adding a link to your repository into README. Thank you so much for sharing your work @kellyi !
